using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bomb : MonoBehaviour
{
    // public AudioClip explosionSound;
    public GameObject explosionPrefab;
    private bool exploded = false;
    // public LayerMask levelMask;
    // Start is called before the first frame update
    void Start()
    {
        Invoke("Explode", 3f);
    }

    void Explode(){
        // AudioSource.PlayClipAtPoint(explosionSound, transform.position);
        Instantiate(explosionPrefab, transform.position, Quaternion.identity);

        StartCoroutine(CreateExplosions(Vector3.forward));
        StartCoroutine(CreateExplosions(Vector3.right));
        StartCoroutine(CreateExplosions(Vector3.back));
        StartCoroutine(CreateExplosions(Vector3.left));

        GetComponent<MeshRenderer>().enabled = false;
        exploded = true;
        transform.Find("Collider").gameObject.SetActive(false);
        Destroy(gameObject, .3f);
    }
    // Update is called once per frame
    public void OnTriggerEnter(Collider other){
        if (!exploded && other.CompareTag("Explosion")) {
            CancelInvoke("Explode");
            Explode();
        }
    }

    private IEnumerator CreateExplosions(Vector3 direction){
        for (int i = 1;i<3;i++){
            RaycastHit hit;
            Physics.Raycast(transform.position + new Vector3(0,.5f,0), direction, out hit);
            if (!hit.collider){
                Instantiate(explosionPrefab, transform.position + (i*direction), explosionPrefab.transform.rotation);
            
            }
            // Instantiate(explosionPrefab, transform.position + (i*direction), explosionPrefab.transform.rotation);
            else if (hit.collider.gameObject.CompareTag("Enemy")){
                Destroy(hit.collider.gameObject);
            }
            else {
                break;
            }
            yield return new WaitForSeconds(.05f);
        }
    }
}
